### ISSUE TITLE
Modifications

### ISSUE THREAD

**Issue by neoxes85** [hugojcastro/HSCardCreator#1]
Hi!
I love your tool, but i have some difficulties to use it. The cardtext font is wrong, can you fix it?
How do you get the images?
Thanks for replying!

**Comment by hugojcastro** [comment]
Hey! Thanks for your support! ^^

I tried to fix cardtext but it seems it depends on third party software (HtmlRenderer) and your system fonts... I made a temporal fix but I'm not sure if the font is the same. To be honest and as it fits my needs, I didn't take it too much into account :_)

About images, I get them from game client using a couple of public tools and a tool I made on my own:
- ExtractDDS (https://github.com/magus/hearthstone-extractdds) to extract files from game client
- Disunity (https://github.com/ata4/disunity) used by ExtractDDS,

And a tool to rename image filenames to the right CardID to be used with my tool. ExtractDDS did it in the past, but the update of Hearthstone to Unity 5 spoiled some things :(

**Comment by neoxes85** [comment]
Yep, unfortunately disunity doesn't work anymore :(
I think we have to wait for an update.

I'm trying to replicate the original images of the game for an Excel project. Hearthpwn is good for english cards, but i need the italian ones, so your tool was very useful. Do you know any other site? Hearthhead images are "strange"...

Anyway, tell me if I can help in some way, even if I'm not an experencied programmer in C#, just an electronics engineer.

**Comment by hugojcastro** [comment]
The last update for **Disunity** works fine, at least to extract textures and text which is all we need :)
Also, you can check the forks for **Disunity** project, because there are a couple with some improvements, just in case ^^

Sadly, all fan sites are too selfish to put their watermark in every card picture, and this is the reason I made this tool. As you can see in my other repository (https://github.com/hugojcastro/HearthStoneHelper), I have another tool to manually (and legally) track deck cards in all locales for _Hearthstone_, so I made all cards by myself for it. You can find them into _images -> cards_ folder. I know the card texts are not the same to the real cards, but it fits for me :)

Again, thanks for your support and kindly words :)

PS: I'll close this issue if you don't mind ^_^U
